### ISSUE TITLE
Add benchmarks page and test suite

### ISSUE THREAD

**Issue by bbarker** [ThoughtWorksInc/Binding.scala#19]
Just a suggestion in case someone wants to have a crack at it (maybe I will, but I doubt ...):

[This](https://www.codementor.io/reactjs/tutorial/reactjs-vs-angular-js-performance-comparison-knockout) might be a good starting point, though note the comment at the bottom that explains the problem with raw dom manipulation.

**Comment by Atry** [comment]
Could you test on Binding.scala 10.0.x if you start to benchmark?

Because I optimized the generated code size and (hopefully) the efficiency.

For example the js file for TodoMVC are reduced from 96.5KB(http://todomvc.com/examples/binding-scala/js/js-opt.js) to 91.7KB (https://thoughtworksinc.github.io/todo/js/js-opt.js)

**Comment by Atry** [comment]
I have created a benchmark and added it to https://github.com/krausest/js-framework-benchmark/pull/94
