### ISSUE TITLE
Vars.all is not triggerred

### ISSUE THREAD

**Issue by Atry** [ThoughtWorksInc/Binding.scala#219]
Originally reported at https://stackoverflow.com/questions//binding-scala-vars-bind-seems-to-not-work-correctly

``` scala
private val test: Vars[Int] = Vars(1,2,3,4)
Binding(test.bind match{case newd => println("TESTS DATAS has changed: " + newd)}).watch
test.value.append(1111)
```

#### Expected
```
TESTS DATAS has changed: Buffer(1, 2, 3, 4)
TESTS DATAS has changed: Buffer(1, 2, 3, 4, 1111)
```

#### Actual
```
TESTS DATAS has changed: Buffer(1, 2, 3, 4)
```

**Comment by datalchemist** [comment]
Thanks for creating the issue! Sorry for not reporting yesterday..I finished the day too busy and so I was going to do it right now :)

I'm not sure however to understand the title of the issue, because the problem I reported seems not to be related to `Vars.all` but to `Vars.bind` and it doesn't work whether we call `Vars.all` before `bind` or not.
But I don't much the implementation and so maybe, you just identified the effective problem more precisely and that's why I don't get the link...

**Comment by Atry** [comment]
This is a regression. According to `git bisect`, 32702dab9cc1b272001e97878b25a670fbf5acf1 is the first bad commit.
